apiVersion: builtin
kind: LabelTransformer
metadata:
  name: label-transformer
labels:
  #istio-injection: enabled
  istio.io/rev: 1-18
fieldSpecs:
- kind: Namespace
  path: metadata/labels
  create: true